### PR TITLE
drop messages if remap loki level is set to false

### LINKED ISSUE #1: I get messages with level "warning", although only "errors" are configured as level.
I have configured the logtarget as follows:

                [
                  'class' => LokiLogTarget::class,
                  ...
                  'levels' => ['error'],
                  ...
                  ],
              ],

i have only set "errors" in levels, but i still get warnings in grafana/loki. Error with level "info" I get correctly not.

image

UPDATE:

messages with level "info" are also displayed

image

UPDATE2:

It only affects the remapped exceptions, which are correctly mapped to warning/info, but are still sent to loki, since apparently the original level ("error") is used for it

                'levelMap' => [
                    // yii category
                    'yii\web\HttpException:404' => [
                        // yii level => loki level
                        '*' => 'info',
                    ],
                    'yii\web\HttpException:401' => [
                        // yii level => loki level
                        '*' => 'warning',
                    ],
                ],

### PR DESCRIPTION
**Pull request by lukassarfert**
closes #1

### CODE REVIEW

File: src/LokiLogTarget.php [hunk 1]
```diff
@@ -120,6 +123,9 @@ public function formatMessage($message)
         list($text, $level, $category, $timestamp) = $message;
         $level = Logger::getLevelName($level);
         $level = $this->remapLevel($level, $category);
+        if ($level == false || $level == 'false') {
```
Comment (cebe) [inline src/LokiLogTarget.php]:
```suggestion
        if ($level === false) {
```

**Review by cebe — APPROVED** [review]

**Comment by cebe** [comment]
Thank you!
